/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_kotlin

import advent_kotlin.infrastructure.DataLoader
import kotlin.test.Test

class DataLoaderTest {
    @Test
    fun readRuckStacks() {
        // Given
        val dataLoader3 = DataLoader("../data/day3_sample.txt")


        // When
        val ruckStacks = dataLoader3.readRuckStacks()

        // Then
        println(ruckStacks)
    }

}
