/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_kotlin

import advent_kotlin.domain.getMarkerIndex
import kotlin.test.Test
import kotlin.test.assertEquals

class MessageMarkerTest {
    @Test
    fun getMarkerIndexWhenMarkerIsLength4() {
        // Given
        val message1 = "bvwbjplbgvbhsrlpgdmjqwftvncz"
        val message2 = "nppdvjthqldpwncqszvftbrmjlhg"
        val message3 = "nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"
        val message4 = "zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"
        val markerLength = 4

        // When + Then
        assertEquals(getMarkerIndex(message1, markerLength), 5)
        assertEquals(getMarkerIndex(message2, markerLength), 6)
        assertEquals(getMarkerIndex(message3, markerLength), 10)
        assertEquals(getMarkerIndex(message4, markerLength), 11)
    }
    @Test
    fun getMarkerIndexWhenMarkerIsLength14() {
        // Given
        val message1 = "mjqjpqmgbljsphdztnvjfqwrcgsmlb"
        val message2 = "bvwbjplbgvbhsrlpgdmjqwftvncz"
        val message3 = "nppdvjthqldpwncqszvftbrmjlhg"
        val message4 = "nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"
        val message5 = "zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"
        val markerLength = 14

            // When + Then
            assertEquals(getMarkerIndex(message1, markerLength), 19)
            assertEquals(getMarkerIndex(message2, markerLength), 23)
        assertEquals(getMarkerIndex(message3, markerLength), 23)
        assertEquals(getMarkerIndex(message4, markerLength), 29)
        assertEquals(getMarkerIndex(message5, markerLength), 26)
    }
}

