/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_kotlin

import advent_kotlin.domain.ElfGroup
import advent_kotlin.domain.RuckStack
import advent_kotlin.domain.getLetterPriority
import kotlin.test.Test
import kotlin.test.assertEquals

class RuckStackTest {
    @Test
    fun getLetterPriorityLowerCase() {
        // Given
        val letter = "p"
        val expectedPriority = 16

        // When
        val priority = getLetterPriority(letter)

        // Then
        assertEquals(expectedPriority, priority)
    }

    @Test
    fun getLetterPriorityUpperCase() {
        // Given
        val letter = "Z"
        val expectedPriority = 52

        // When
        val priority = getLetterPriority(letter)

        // Then
        assertEquals(expectedPriority, priority)
    }

    @Test
    fun getElfGroupBadge() {
        // Given
        val elfGroup = ElfGroup(
            RuckStack("vJrwpWtwJgWr".chunked(1), "hcsFMMfFFhFp".chunked(1)),
            RuckStack("jqHRNqRjqzjGDLGL".chunked(1), "rsFMfFZSrLrFZsSL".chunked(1)),
            RuckStack("PmmdzqPrV".chunked(1), "vPwwTWBwg".chunked(1))
        )
        val expectedBadge = "r"
        // When
        val badge = elfGroup.getBadge()

        // Then
        assertEquals(expectedBadge, badge)
    }
}

