/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_kotlin

import advent_kotlin.domain.Position
import advent_kotlin.domain.VentLine
import advent_kotlin.domain.VentLines
import kotlin.test.*

class VentLinesTest {
    @Test
    fun getNumberOfLineWhen2() {
        // Given
        val ventLines = VentLines(
            listOf(
                VentLine(Position(0, 1), Position(0, 3)),
                VentLine(Position(0, 1), Position(3, 1))
            ))

        val position = Position (0, 1)
        val expectedNumberOfLines = 2

        // When
        val numberOfLines = ventLines.getNumberOfLine(position)

        // Then
        assertEquals(expectedNumberOfLines, numberOfLines)
    }
    @Test
    fun getNumberOfLineWhen1() {
        // Given
        val ventLines = VentLines(
            listOf(
                VentLine(Position(0, 1), Position(0, 3)),
                VentLine(Position(0, 1), Position(3, 1))
            ))

        val position = Position (0, 3)
        val expectedNumberOfLines = 1

        // When
        val numberOfLines = ventLines.getNumberOfLine(position)

        // Then
        assertEquals(expectedNumberOfLines, numberOfLines)
    }
    @Test
    fun getNumberOfLineWhen0() {
        // Given
        val ventLines = VentLines(
            listOf(
                VentLine(Position(0, 1), Position(0, 3)),
                VentLine(Position(0, 1), Position(3, 1))
            ))

        val position = Position (5, 3)
        val expectedNumberOfLines = 0

        // When
        val numberOfLines = ventLines.getNumberOfLine(position)

        // Then
        assertEquals(expectedNumberOfLines, numberOfLines)
    }
}
